### PR TITLE
feat: added precommit hook for eslint

### PR DESCRIPTION
**Pull request by HunterJS-bit**
## Describe your changes
Added pre-comit hook for **Eslint**
Added husky & lint-staged packages

## Issue ticket number and link
#17 

## Checklist before requesting a review
- [X ] I have performed a self-review of my code

### CODE REVIEW

**Review by nathan-barrett — CHANGES_REQUESTED** [review]
Looks good, I think we'll just need to also lint `.jsx` files in addition to files with `.js` extensions

**Comment by HunterJS-bit** [comment]
Will update today

**Comment by HunterJS-bit** [comment]
@nathan-barrett Updated PR, included `jsx` files in linting

**Comment by HunterJS-bit** [comment]
@nathan-barrett Is it ok now, can it be merged?

**Comment by nathan-barrett** [comment]
@HunterJS-bit Looks good, it might need to be rebased since it looks like there is a conflict in package-lock.json. Apologies for taking so long to look at this since I was out of town for the last few weeks!

**Review by nathan-barrett — APPROVED** [review]

**Comment by HunterJS-bit** [comment]
> @HunterJS-bit Looks good, it might need to be rebased since it looks like there is a conflict in package-lock.json. Apologies for taking so long to look at this since I was out of town for the last few weeks!
Understand completely :), its done.. feel free to merge it when you have time or if you allow I can :)

**Pull request merged**
